/* Dehnen: Übungsbibliothek und Empfehlung (Skizzen: shared/figur.js). */
(function () {
  "use strict";

  const REGIONS = { huefte: "Hüftbeuger & Hüfte", vorn: "Oberschenkel vorn", hinten: "Oberschenkel hinten", wade: "Waden & Füße",
    gesaess: "Gesäß & Adduktoren", ruecken: "Rücken & Rumpf", schulter: "Schulter & Brust" };
  const EQUIP = { ohne: "ohne Hilfsmittel", wand: "Wand / Halt", box: "Bank / Erhöhung", band: "Band / Gurt" };
  // goal = Anlass, level = Niveau (keine Trainingsphase)
  const GOALS = { warm: "Aufwärmen", post: "Nach dem Training", mob: "Beweglichkeitseinheit" };
  const LEVELS = { ein: "Einsteiger", fort: "Fortgeschritten", leist: "Leistungssport" };
  const DEFAULTS = { goal: "post", level: "fort" };

  /* kind: static = halten (Sekunden), dynamic = schwingen/bewegen (Wiederholungen). Posen wie in shared/kraft.js. */
  const EX = [
    { id: "hueftbeuger", name: "Hüftbeuger im Kniestand", region: "huefte", equip: ["ohne"], level: 1, kind: "static", side: true,
      muscles: "Hüftbeuger (Iliopsoas), Oberschenkel vorn",
      why: "Verkürzte Hüftbeuger bremsen die Hüftstreckung im Sprint und fördern ein Hohlkreuz.",
      steps: ["Kniestand im Ausfallschritt, vorderes Knie über dem Fuß, hinteres Knie auf weicher Unterlage.", "Becken aufrichten (Gesäß anspannen), dann die Hüfte langsam nach vorn schieben.", "Dehnung vorn in der Leiste halten, ruhig atmen."],
      cues: ["Kein Hohlkreuz – Becken bleibt aufgerichtet", "Oberkörper aufrecht", "Dehnung in der Leiste, nicht im Rücken"],
      easier: "Kleinerer Schritt, Hände auf dem vorderen Knie", harder: "Arm der hinteren Seite nach oben strecken und leicht zur Seite neigen",
      poses: [{ t: 0, l1: [85, 0], l2: [-14, -90], r1: [32, 40], r2: [34, 42] }, { t: -6, l1: [68, -12], l2: [-38, -90], r1: [40, 50], r2: [42, 52] }],
      ax: "k2", x: 40 },
    { id: "couch", name: "Couch Stretch", region: "huefte", equip: ["wand"], level: 3, kind: "static", side: true,
      muscles: "Hüftbeuger, gerader Oberschenkelmuskel (Rectus femoris)",
      why: "Intensive Dehnung für Hüftbeuger und vorderen Oberschenkel zugleich – typische Problemzone bei Sprintern.",
      steps: ["Hinteres Knie nah an der Wand (oder am Sofa), der Unterschenkel lehnt senkrecht an der Wand.", "Vorderer Fuß steht im Ausfallschritt vorn.", "Langsam den Oberkörper aufrichten, bis eine deutliche Dehnung vorn spürbar ist."],
      cues: ["Gesäß anspannen, Becken aufrichten", "Nur so weit aufrichten, wie es ohne Schmerz geht", "Weiche Unterlage unter dem Knie"],
      easier: "Oberkörper vorgeneigt lassen, Hände auf einer Erhöhung", harder: "Ganz aufrichten, Arme nach oben",
      poses: [{ t: 32, l1: [85, -2], l2: [-18, 180], r1: [10, 20], r2: [12, 22] }, { t: 0, l1: [85, -2], l2: [-18, 180], r1: [35, 40], r2: [37, 42] }],
      props: [{ t: "wallJ", at: "a2", dx: -4 }], ax: "k2", x: 34 },
    { id: "quad", name: "Oberschenkel vorn im Stand", region: "vorn", equip: ["ohne", "wand"], level: 1, kind: "static", side: true,
      muscles: "Oberschenkel vorn (Quadrizeps), Hüftbeuger",
      why: "Entlastet Knie und Hüfte nach Sprints und Sprüngen.",
      steps: ["Auf einem Bein stehen, mit der anderen Hand an der Wand abstützen.", "Ferse zum Gesäß ziehen und den Fuß mit der Hand fassen.", "Knie zeigt nach unten, Becken leicht nach vorn schieben."],
      cues: ["Knie bleiben nebeneinander", "Kein Hohlkreuz", "Standbein leicht gebeugt"],
      easier: "Mit Band oder Handtuch um den Fuß", harder: "In Seitlage oder als Couch Stretch",
      poses: [{ t: 2, l1: [-22, -160], l2: [2, 0], r1: [-28, -40], r2: [82, 88] }], ax: "a2", x: 56 },
    { id: "hamstring", name: "Oberschenkel hinten mit Bein auf Erhöhung", region: "hinten", equip: ["box"], level: 1, kind: "static", side: true,
      muscles: "Oberschenkel hinten (Hamstrings), Wade",
      why: "Elastische Hamstrings sind wichtig für den raumgreifenden Sprintschritt und schützen vor Zerrungen.",
      steps: ["Ferse eines gestreckten Beins auf eine Erhöhung (Kniehöhe) legen, Fußspitze zeigt nach oben.", "Mit geradem Rücken aus der Hüfte nach vorn neigen.", "Dehnung hinten im Oberschenkel halten."],
      cues: ["Rücken bleibt gerade – Bewegung aus der Hüfte", "Standbein und Becken zeigen nach vorn", "Kein Federn"],
      easier: "Niedrigere Erhöhung, Knie leicht gebeugt", harder: "Fußspitze zu dir ziehen",
      poses: [{ t: 5, l1: [90, 90], l2: [0, 0], r1: [40, 60], r2: [42, 62], f1: 165 }, { t: 38, l1: [90, 90], l2: [0, 0], r1: [72, 82], r2: [74, 84], f1: 165 }],
      props: [{ t: "boxUnder", at: "a1", w: 14, dx: 2, dy: 2 }], anchor: ["a2", 92], ax: "a2", x: 36 },
    { id: "hamstringband", name: "Oberschenkel hinten liegend mit Band", region: "hinten", equip: ["band"], level: 1, kind: "static", side: true,
      muscles: "Oberschenkel hinten, Wade",
      why: "Schonende Hamstring-Dehnung ohne Belastung des Rückens – gut nach dem Training.",
      steps: ["Rückenlage, ein Band oder Handtuch um den Fuß des oberen Beins.", "Bein gestreckt nach oben ziehen, bis eine Dehnung hinten spürbar ist.", "Das andere Bein bleibt gestreckt am Boden."],
      cues: ["Knie des gedehnten Beins gestreckt", "Becken bleibt am Boden", "Schultern entspannt"],
      easier: "Unteres Bein aufgestellt", harder: "Fußspitze zusätzlich Richtung Schienbein ziehen",
      poses: [{ t: -90, l1: [140, 140], l2: [92, 92], r1: [150, 150], r2: [152, 152] }, { t: -90, l1: [172, 172], l2: [92, 92], r1: [168, 160], r2: [170, 162] }],
      props: [{ t: "strap", at: "h1", to: "t1" }], ax: "p", x: 52 },
    { id: "wade", name: "Wade gestreckt an der Wand", region: "wade", equip: ["wand"], level: 1, kind: "static", side: true,
      muscles: "Wade (Zwillingswadenmuskel)",
      why: "Lockere Waden entlasten Achillessehne und Schienbein bei vielen Sprüngen und Sprints.",
      steps: ["Hände an der Wand, ein Bein weit nach hinten stellen.", "Hintere Ferse bleibt am Boden, Knie gestreckt.", "Hüfte nach vorn zur Wand schieben."],
      cues: ["Hinterer Fuß zeigt gerade nach vorn", "Ferse bleibt am Boden", "Körper bildet eine Linie"],
      easier: "Kürzerer Schritt", harder: "Fußballen auf eine Stufe, Ferse absenken",
      poses: [{ t: 26, l1: [26, -6], l2: [-24, -24], r1: [76, 86], r2: [78, 88] }], props: [{ t: "wallJ", at: "h1", dx: 3 }], ax: "a2", x: 28 },
    { id: "soleus", name: "Wade gebeugt (Achillessehne)", region: "wade", equip: ["wand"], level: 1, kind: "static", side: true,
      muscles: "Schollenmuskel (Soleus), Achillessehne",
      why: "Erreicht den tiefen Wadenmuskel, der beim Laufen die meiste Arbeit leistet.",
      steps: ["Schrittstellung vor der Wand, Hände an der Wand.", "Beide Knie beugen, hintere Ferse bleibt am Boden.", "Gewicht nach vorn-unten verlagern, bis die Dehnung tief in der Wade spürbar ist."],
      cues: ["Ferse bleibt unten", "Knie zeigt über die Fußspitze", "Langsam steigern"],
      easier: "Weniger tief beugen", harder: "Fußspitze an die Wand gestellt",
      poses: [{ t: 18, l1: [22, -12], l2: [-2, -30], r1: [70, 84], r2: [72, 86] }], props: [{ t: "wallJ", at: "h1", dx: 3 }], ax: "a2", x: 34 },
    { id: "taube", name: "Taube", region: "gesaess", equip: ["ohne"], level: 2, kind: "static", side: true,
      muscles: "Gesäß, äußere Hüftrotatoren, Hüftbeuger der hinteren Seite",
      why: "Öffnet die Hüfte – für einen freien, runden Laufstil.",
      steps: ["Aus dem Vierfüßlerstand ein Knie nach vorn zwischen die Hände bringen, Unterschenkel quer vor dem Körper.", "Hinteres Bein gestreckt nach hinten ablegen.", "Becken gerade absenken, Oberkörper aufrecht oder nach vorn ablegen."],
      cues: ["Becken bleibt gerade", "Kein Schmerz im vorderen Knie", "Ruhig atmen und loslassen"],
      easier: "Kissen unter die Hüfte der vorderen Seite", harder: "Oberkörper flach nach vorn ablegen",
      poses: [{ t: 18, l1: [82, -90], l2: [-95, -95], r1: [10, 0], r2: [12, 2], f2: 0 }], ax: "k1", x: 70 },
    { id: "schmetterling", name: "Schmetterlingssitz", region: "gesaess", equip: ["ohne"], level: 1, kind: "static",
      muscles: "Adduktoren (Oberschenkel innen)",
      why: "Beweglichere Adduktoren senken das Risiko für Leistenprobleme.",
      steps: ["Aufrecht sitzen, Fußsohlen aneinander, Fersen nah zum Körper.", "Füße mit den Händen fassen.", "Knie entspannt Richtung Boden sinken lassen, Rücken gerade."],
      cues: ["Rücken gerade, nicht rund", "Knie nicht mit den Armen herunterdrücken", "Fersen näher = intensiver"],
      easier: "Fersen weiter weg, Rücken an die Wand", harder: "Mit geradem Rücken leicht nach vorn neigen",
      poses: [{ t: 0, l1: [72, -58], l2: [-72, 58], r1: [14, -8], r2: [-14, 8], front: true }], ax: "p", x: 60, view: "Frontansicht" },
    { id: "seitausfall", name: "Tiefer Seitausfall", region: "gesaess", equip: ["ohne"], level: 2, kind: "static", side: true,
      muscles: "Adduktoren, Gesäß",
      why: "Dehnt die Innenseite des gestreckten Beins und kräftigt gleichzeitig das gebeugte.",
      steps: ["Weiter Grätschstand, Füße zeigen nach vorn.", "Gewicht auf ein Bein verlagern und dieses tief beugen.", "Das andere Bein bleibt gestreckt, Fußsohle am Boden."],
      cues: ["Ferse des gebeugten Beins bleibt unten", "Rücken gerade", "Gestrecktes Knie zeigt nach oben"],
      easier: "Weniger tief, Hände auf dem Knie", harder: "Fußspitze des gestreckten Beins anziehen",
      poses: [{ t: 8, l1: [42, -12], l2: [-62, -62], r1: [36, 20], r2: [20, 30], front: true }], ax: "a1", x: 84, view: "Frontansicht" },
    { id: "tractus", name: "Hüfte seitlich im Stand", region: "huefte", equip: ["ohne"], level: 1, kind: "static", side: true,
      muscles: "Seitliche Hüfte, Tractus iliotibialis, Flanke",
      why: "Lockert die Außenseite von Hüfte und Oberschenkel – häufig verspannt bei Läufern.",
      steps: ["Die Beine im Stand überkreuzen, das hintere Bein ist die Dehnseite.", "Hüfte zur Dehnseite schieben.", "Oberkörper und Arm zur Gegenseite neigen."],
      cues: ["Nicht nach vorn beugen", "Beide Füße am Boden", "Dehnung seitlich an der Hüfte"],
      easier: "Mit Hand an der Wand", harder: "Weiter neigen, Arm lang über den Kopf",
      poses: [{ t: -16, l1: [-12, -12], l2: [12, 12], r1: [30, -50], r2: [200, 210], front: true }], ax: "p", x: 60, view: "Frontansicht" },
    { id: "kind", name: "Kindhaltung", region: "ruecken", equip: ["ohne"], level: 1, kind: "static",
      muscles: "Unterer Rücken, breiter Rückenmuskel, Gesäß",
      why: "Entspannt den Rücken nach Sprüngen und Krafttraining.",
      steps: ["Kniestand, Gesäß auf die Fersen setzen.", "Oberkörper nach vorn auf die Oberschenkel ablegen.", "Arme lang nach vorn strecken, Stirn zum Boden."],
      cues: ["Gesäß bleibt auf den Fersen", "Tief in den Rücken atmen", "Schultern locker"],
      easier: "Kissen zwischen Gesäß und Fersen", harder: "Hände zu einer Seite wandern lassen (seitliche Dehnung)",
      poses: [{ t: 104, l1: [38, -90], l2: [40, -88], r1: [104, 96], r2: [106, 98], f1: 0, f2: 0 }], ax: "k1", x: 52 },
    { id: "kobra", name: "Kobra", region: "ruecken", equip: ["ohne"], level: 1, kind: "static",
      muscles: "Gerader Bauchmuskel, Hüftbeuger",
      why: "Gegenbewegung zu langem Sitzen und vielen Bauchübungen.",
      steps: ["Bauchlage, Hände neben den Schultern.", "Oberkörper mit den Armen langsam aufrichten, Becken bleibt am Boden.", "Schultern tief, Blick nach vorn."],
      cues: ["Nur so weit, wie der Rücken es angenehm zulässt", "Gesäß locker", "Schultern weg von den Ohren"],
      easier: "Auf die Unterarme stützen (Sphinx)", harder: "Arme fast ganz strecken",
      poses: [{ t: 52, l1: [-92, -92], l2: [-91, -91], r1: [-12, 14], r2: [-10, 16], f1: 0, f2: 0 }], ax: "p", x: 52 },
    { id: "brust", name: "Brust an der Wand", region: "schulter", equip: ["wand"], level: 1, kind: "static", side: true,
      muscles: "Brustmuskel, vordere Schulter",
      why: "Gegen nach vorn gezogene Schultern – für einen freien Armschwung.",
      steps: ["Seitlich neben eine Wand oder in einen Türrahmen stellen.", "Unterarm oder Hand auf Schulterhöhe an die Wand legen.", "Oberkörper langsam von der Wand wegdrehen."],
      cues: ["Schulter tief halten", "Nicht ins Hohlkreuz", "Langsam drehen"],
      easier: "Arm tiefer ansetzen", harder: "Arm etwas höher, weiter drehen",
      poses: [{ t: 3, l1: [12, 0], l2: [-8, 0], r1: [-90, -90], r2: [8, 8] }], props: [{ t: "wallJ", at: "h1", dx: -2 }], ax: "a1", x: 72 },
    { id: "schulterquer", name: "Schulter hinten (Arm vor der Brust)", region: "schulter", equip: ["ohne"], level: 1, kind: "static", side: true,
      muscles: "Hintere Schulter, oberer Rücken",
      why: "Lockert die Schulter nach Würfen, Klimmzügen und Rudern.",
      steps: ["Aufrecht stehen, einen Arm gestreckt vor der Brust zur Gegenseite führen.", "Mit der anderen Hand am Oberarm (nicht am Ellbogen) heranziehen.", "Halten, Seite wechseln."],
      cues: ["Schulter bleibt tief", "Oberkörper nicht mitdrehen", "Nur sanfter Zug"],
      easier: "Weniger Zug", harder: "Schulterblatt bewusst nach vorn schieben",
      poses: [{ t: 0, l1: [8, 0], l2: [-8, 0], r1: [-95, -95], r2: [-30, -150], front: true }], ax: "p", x: 62, view: "Frontansicht" },
    { id: "flanke", name: "Flanke und Trizeps", region: "schulter", equip: ["ohne"], level: 1, kind: "static", side: true,
      muscles: "Breiter Rückenmuskel, seitlicher Rumpf, Trizeps",
      why: "Dehnt die Seite vom Becken bis zum Arm – für einen langen, lockeren Rumpf.",
      steps: ["Hüftbreit stehen, einen Arm gestreckt über den Kopf.", "Oberkörper zur Gegenseite neigen.", "Die freie Hand stützt sich an der Hüfte ab."],
      cues: ["Nicht nach vorn oder hinten kippen", "Becken bleibt mittig", "Lang machen statt nur neigen"],
      easier: "Weniger weit neigen", harder: "Ellbogen beugen und mit der anderen Hand ziehen (Trizeps)",
      poses: [{ t: -20, l1: [9, 0], l2: [-9, 0], r1: [196, 200], r2: [-30, 40], front: true }], ax: "p", x: 60, view: "Frontansicht" },

    // ---------- dynamisch ----------
    { id: "beinpendel", name: "Beinpendel vor und zurück", region: "hinten", equip: ["wand"], level: 1, kind: "dynamic", side: true,
      muscles: "Hüftbeuger, Oberschenkel hinten, Gesäß",
      why: "Bereitet die Hüfte auf große Schrittamplituden vor – ideal im Aufwärmen.",
      steps: ["Seitlich an der Wand abstützen, auf einem Bein stehen.", "Das freie Bein locker vor und zurück pendeln.", "Die Bewegungsweite von Schwung zu Schwung steigern."],
      cues: ["Oberkörper bleibt aufrecht", "Locker aus der Hüfte schwingen", "Standbein leicht gebeugt"],
      easier: "Kleinere Bewegung", harder: "Höher und schneller pendeln",
      poses: [{ t: 2, l1: [-34, -38], l2: [0, 0], r1: [78, 88], r2: [-10, -10] }, { t: -4, l1: [70, 66], l2: [0, 0], r1: [78, 88], r2: [-10, -10] }],
      props: [{ t: "wallJ", at: "h1", dx: 3 }], ax: "a2", x: 42 },
    { id: "beinpendelseit", name: "Beinpendel seitlich", region: "gesaess", equip: ["wand"], level: 1, kind: "dynamic", side: true,
      muscles: "Adduktoren, seitliche Hüfte",
      why: "Mobilisiert die Hüfte seitlich – vor Sprints, Hürden und Sprüngen.",
      steps: ["Mit beiden Händen vor einer Wand abstützen.", "Ein Bein vor dem Standbein seitlich hin und her pendeln.", "Bewegungsweite langsam steigern."],
      cues: ["Becken bleibt ruhig und gerade", "Standbein leicht gebeugt", "Rhythmisch und locker"],
      easier: "Kleinere Bewegung", harder: "Größere Bewegungsweite",
      poses: [{ t: 0, l1: [-24, -24], l2: [0, 0], r1: [24, 20], r2: [-24, -20], front: true }, { t: 0, l1: [42, 42], l2: [0, 0], r1: [24, 20], r2: [-24, -20], front: true }],
      ax: "a2", x: 52, view: "Frontansicht" },
    { id: "wgs", name: "Ausfallschritt mit Rotation", region: "huefte", equip: ["ohne"], level: 2, kind: "dynamic", side: true,
      muscles: "Hüftbeuger, Adduktoren, Brustwirbelsäule, Schulter",
      why: "„World's Greatest Stretch“: mobilisiert Hüfte, Rücken und Schulter in einer Übung – perfekt im Aufwärmen.",
      steps: ["Großer Ausfallschritt, beide Hände innen neben dem vorderen Fuß.", "Den inneren Arm zur Decke drehen, Blick folgt der Hand.", "Hand zurück, nächster Schritt mit dem anderen Bein."],
      cues: ["Hinteres Bein gestreckt", "Drehung aus dem Brustkorb", "Ruhig ausatmen beim Aufdrehen"],
      easier: "Hinteres Knie absetzen", harder: "Vor dem Aufdrehen den Ellbogen zum Fußknöchel führen",
      poses: [{ t: 72, l1: [86, -6], l2: [-44, -44], r1: [0, 0], r2: [2, 2] }, { t: 58, l1: [86, -6], l2: [-44, -44], r1: [178, 180], r2: [2, 2] }],
      ax: "a2", x: 22, view: "Rotation zur Seite" },
    { id: "raupe", name: "Raupe (Inchworm)", region: "hinten", equip: ["ohne"], level: 2, kind: "dynamic",
      muscles: "Oberschenkel hinten, Waden, Schultern, Rumpf",
      why: "Dehnt die hintere Kette und aktiviert Schultern und Rumpf – ideal zu Beginn des Aufwärmens.",
      steps: ["Aus dem Stand mit gestreckten Beinen nach vorn beugen, Hände auf den Boden.", "Mit den Händen nach vorn laufen bis in den Liegestütz.", "Mit kleinen Schritten die Füße zu den Händen nachlaufen."],
      cues: ["Knie möglichst gestreckt", "Im Stütz Körper gerade", "Langsam und kontrolliert"],
      easier: "Knie leicht beugen", harder: "Im Stütz einen Liegestütz einbauen",
      poses: [{ t: 136, l1: [0, 0], l2: [2, 2], r1: [0, 0], r2: [2, 2], f1: 90 }, { t: 70, l1: [-70, -70], l2: [-69, -69], r1: [0, 0], r2: [2, 2], f1: 0, f2: 0 }],
      ax: "h1", x: 84 },
    { id: "kniebrust", name: "Knie zur Brust im Gehen", region: "gesaess", equip: ["ohne"], level: 1, kind: "dynamic", side: true,
      muscles: "Gesäß, Oberschenkel hinten",
      why: "Öffnet Gesäß und Hüfte und schult das Gleichgewicht – für den Kniehub im Sprint.",
      steps: ["Im Gehen ein Knie anheben und mit beiden Händen zur Brust ziehen.", "Gleichzeitig auf die Zehenspitzen des Standbeins kommen.", "Absetzen, mit dem anderen Bein weitergehen."],
      cues: ["Oberkörper aufrecht", "Kurz halten, dann weiter", "Standbein gestreckt"],
      easier: "Ohne Zehenstand", harder: "Am Ende des Zugs in den Ausfallschritt",
      poses: [{ t: 0, l1: [2, 0], l2: [-2, 0], r1: [4, 4], r2: [-4, -4] }, { t: -2, l1: [148, -6], l2: [0, 0], r1: [52, 128], r2: [56, 132], f2: 45 }],
      ax: "a2", x: 52 },
    { id: "sweep", name: "Hamstring-Sweep im Gehen", region: "hinten", equip: ["ohne"], level: 1, kind: "dynamic", side: true,
      muscles: "Oberschenkel hinten, Wade",
      why: "Dynamische Dehnung der Oberschenkelrückseite – sanfter Einstieg vor Sprints.",
      steps: ["Ein Bein gestreckt nach vorn setzen, Ferse am Boden, Fußspitze hoch.", "Mit geradem Rücken nach vorn beugen und die Hände am Boden entlang nach vorn fegen.", "Aufrichten, nächster Schritt mit dem anderen Bein."],
      cues: ["Rücken gerade", "Vorderes Knie gestreckt", "Fließende Bewegung"],
      easier: "Weniger tief beugen", harder: "Schneller und rhythmischer",
      poses: [{ t: 0, l1: [22, 22], l2: [-4, -4], r1: [170, 172], r2: [168, 170], f1: 150 }, { t: 74, l1: [22, 22], l2: [-4, -4], r1: [20, 30], r2: [22, 32], f1: 150 }],
      ax: "a2", x: 40 },
    { id: "armkreisen", name: "Armkreisen", region: "schulter", equip: ["ohne"], level: 1, kind: "dynamic",
      muscles: "Schultern, Brust, oberer Rücken",
      why: "Bereitet die Schultern auf den kräftigen Armeinsatz im Sprint vor.",
      steps: ["Aufrecht stehen.", "Gestreckte Arme in großen Kreisen nach hinten führen.", "Danach die Richtung wechseln."],
      cues: ["Große, ruhige Kreise", "Kein Hohlkreuz", "Schultern locker"],
      easier: "Kleine Kreise oder einarmig", harder: "Gegengleich (ein Arm vor, einer zurück)",
      poses: [{ t: 0, l1: [3, 0], l2: [-3, 0], r1: [-30, -30], r2: [-28, -28] }, { t: 0, l1: [3, 0], l2: [-3, 0], r1: [180, 180], r2: [182, 182] }],
      ax: "a1", x: 56 },
  ];
  const BY_ID = new Map(EX.map((e) => [e.id, e]));

  /* ---------- Empfehlung ---------- */
  // [Durchgänge, von, bis, Pause/Wechsel s, Hinweis]
  const BASE = {
    static: { warm: [1, 15, 20, 0, "nur kurz – längeres statisches Dehnen direkt vor Sprints kann die Schnellkraft mindern; besser dynamisch"],
      post: [2, 30, 30, 10, "angenehme Dehnspannung, ruhig atmen"], mob: [3, 45, 60, 15, "langsam steigern, Spannung etwa 6–7 von 10"] },
    dynamic: { warm: [2, 10, 12, 15, "kontrolliert, Bewegungsweite von Mal zu Mal steigern"],
      post: [1, 8, 10, 0, "locker zum Auslaufen"], mob: [2, 12, 15, 15, "volle Bewegungsweite, langsam"] },
  };
  const UNIT = { static: "s", dynamic: "Wdh." };
  function dose(ex, cfg, age) {
    const c = Object.assign({}, DEFAULTS), cf = cfg || {};
    if (GOALS[cf.goal]) c.goal = cf.goal; if (LEVELS[cf.level]) c.level = cf.level;
    let [sets, lo, hi, rest, hint] = BASE[ex.kind][c.goal];
    const notes = [];
    if (c.level === "ein") { sets = Math.min(sets, 2); if (ex.kind === "static" && c.goal !== "warm") { lo = Math.round(lo * 0.75); hi = Math.round(hi * 0.75); } notes.push("Einsteiger: kürzer halten"); }
    if (c.level === "leist" && c.goal === "mob") { sets += 1; notes.push("Leistungssport: ein Durchgang mehr"); }
    if (age != null && age >= 50 && ex.kind === "static" && c.goal !== "warm") { lo += 15; hi += 15; notes.push("Masters 50+: länger halten (wirkt nachweislich besser)"); }
    if (ex.kind === "static") { lo = Math.round(lo / 5) * 5; hi = Math.round(hi / 5) * 5; }
    return { sets, reps: lo === hi ? String(lo) : lo + "–" + hi, unit: UNIT[ex.kind], side: !!ex.side, rest, hint, notes };
  }
  const fmtRest = (s) => (s >= 60 ? (s % 60 ? Math.floor(s / 60) + ":" + String(s % 60).padStart(2, "0") + " min" : s / 60 + " min") : s + " s");

  window.LA_DEHNEN = { id: "dehnen", REGIONS, EQUIP, GOALS, LEVELS, PHASES: null, DEFAULTS, EX, BY_ID, sketch: LA_FIGUR.sketch, dose, fmtRest, UNIT,
    text: { title: "Dehnen", goal: "Anlass", level: "Niveau", phase: null, start: "Dehnprogramm starten",
      run: "Dehnprogramm", runHint: "„▶ halten“ startet die Haltezeit; bei dynamischen Übungen Durchgang antippen.", done: "Dehnprogramm abschließen",
      sub: "Statische und dynamische Dehnübungen mit Skizze, Erklärung und Empfehlung. Mit ☆ stellst du dir dein Programm zusammen.",
      empty: "z. B. 6 bis 10 Übungen aus allen Bereichen", unitSets: "Durchgänge", unitOne: "Durchgang", skipCoverage: [],
      restBetween: "Pause bzw. Seitenwechsel", hintLabel: "Hinweis", stillNote: "Dehnposition – wie gezeigt halten.",
      ageNote: "statische Dehnungen länger halten (Masters 50+).", loadLabel: "Hilfsmittel", loadPh: "z. B. Band, Kissen" } };
})();
